### ISSUE TITLE
Also consider "README" files without extension

### ISSUE THREAD

**Issue by luator** [machines-in-motion/breathing-cat#7]
We should also look for "README" and assume markdown

_Originally posted by @MaximilienNaveau in https://github.com/machines-in-motion/breathing-cat/pull/6#discussion_r992141526_

**Comment by luator** [comment]
Maybe also consider "README.txt" (probably also assume markdown in this case).

**Comment by luator** [comment]
@MaximilienNaveau 
Another option I'm currently thinking about is to add README/README.txt as "literal" include.  It will then be shown like this:
![image](https://user-images.githubusercontent.com/9333121/195093810-e58ee2a2-6971-415c-b2d6-4b26f722cb85.png)

It might be safer than just assuming some format and would also indicate the problem to the user in case the extension was accidentally left out (if the user wants it to be Markdown, they should properly call it "REAME.md" after all).

What do you think?

**Comment by MaximilienNaveau** [comment]
That's nice
